#!/bin/sh

set -e

echo "Adding linux-image debug symbols."
if [ "$(lsb_release -is)" = "Debian" ]; then
    apt-get update
    apt-get install linux-image-$(uname -r)-dbg
elif [ "$(lsb_release -is)" = "Ubuntu" ]; then
    sudo tee /etc/apt/sources.list.d/ddebs.list << EOF
    deb http://ddebs.ubuntu.com/ $(lsb_release -cs)          main
    deb http://ddebs.ubuntu.com/ $(lsb_release -cs)-updates  main
EOF
    # avoid stderr output
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ECDCAD72428D7C01 2>&1
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q linux-image-$(uname -r)-dbgsym
fi

echo "Testing crash on live kernel"
crash -st /usr/lib/debug/boot/vmlinux-$(uname -r) 2>&1
